# Generated by Django 4.2.5 on 2023-09-25 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_info_animal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="animals",
            name="short_description",
        ),
    ]
